; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu | FileCheck %s --check-prefix=X64
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+bmi2 | FileCheck %s --check-prefix=BMI2

; Squaring of wide integers (mul x, x): the cross products are computed once
; and doubled, and the partial products are added along the anti-diagonals.

; truncated square, 4 x 4 limbs
define void @sqr_i256(ptr %out, ptr %in) {
; X64-LABEL: sqr_i256:
; X64:       # %bb.0:
; X64-NEXT:    pushq %rbx
; X64-NEXT:    .cfi_def_cfa_offset 16
; X64-NEXT:    .cfi_offset %rbx, -16
; X64-NEXT:    movq 16(%rsi), %rbx
; X64-NEXT:    movq (%rsi), %r9
; X64-NEXT:    movq 8(%rsi), %r8
; X64-NEXT:    movq %r9, %rax
; X64-NEXT:    mulq %r9
; X64-NEXT:    movq %rdx, %rcx
; X64-NEXT:    movq %rax, (%rdi)
; X64-NEXT:    movq 24(%rsi), %r11
; X64-NEXT:    imulq %r9, %r11
; X64-NEXT:    movq %r9, %rax
; X64-NEXT:    mulq %rbx
; X64-NEXT:    movq %rax, %rsi
; X64-NEXT:    movq %rdx, %r10
; X64-NEXT:    addq %r11, %r10
; X64-NEXT:    movq %r9, %rax
; X64-NEXT:    mulq %r8
; X64-NEXT:    movq %rax, %r9
; X64-NEXT:    movq %rdx, %r11
; X64-NEXT:    imulq %r8, %rbx
; X64-NEXT:    addq %rsi, %r11
; X64-NEXT:    adcq %r10, %rbx
; X64-NEXT:    shldq $1, %r11, %rbx
; X64-NEXT:    shldq $1, %rax, %r11
; X64-NEXT:    addq %rax, %r9
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    mulq %r8
; X64-NEXT:    addq %rcx, %r9
; X64-NEXT:    movq %r9, 8(%rdi)
; X64-NEXT:    adcq %r11, %rax
; X64-NEXT:    movq %rax, 16(%rdi)
; X64-NEXT:    adcq %rbx, %rdx
; X64-NEXT:    movq %rdx, 24(%rdi)
; X64-NEXT:    popq %rbx
; X64-NEXT:    .cfi_def_cfa_offset 8
; X64-NEXT:    retq
;
; BMI2-LABEL: sqr_i256:
; BMI2:       # %bb.0:
; BMI2-NEXT:    movq 16(%rsi), %rcx
; BMI2-NEXT:    movq (%rsi), %rdx
; BMI2-NEXT:    movq 8(%rsi), %rax
; BMI2-NEXT:    mulxq %rdx, %r9, %r8
; BMI2-NEXT:    movq %r9, (%rdi)
; BMI2-NEXT:    movq 24(%rsi), %rsi
; BMI2-NEXT:    imulq %rdx, %rsi
; BMI2-NEXT:    mulxq %rcx, %r9, %r10
; BMI2-NEXT:    addq %rsi, %r10
; BMI2-NEXT:    mulxq %rax, %rdx, %rsi
; BMI2-NEXT:    imulq %rax, %rcx
; BMI2-NEXT:    addq %r9, %rsi
; BMI2-NEXT:    adcq %r10, %rcx
; BMI2-NEXT:    shldq $1, %rsi, %rcx
; BMI2-NEXT:    shldq $1, %rdx, %rsi
; BMI2-NEXT:    addq %rdx, %rdx
; BMI2-NEXT:    addq %r8, %rdx
; BMI2-NEXT:    movq %rdx, 8(%rdi)
; BMI2-NEXT:    movq %rax, %rdx
; BMI2-NEXT:    mulxq %rax, %rax, %rdx
; BMI2-NEXT:    adcq %rsi, %rax
; BMI2-NEXT:    movq %rax, 16(%rdi)
; BMI2-NEXT:    adcq %rcx, %rdx
; BMI2-NEXT:    movq %rdx, 24(%rdi)
; BMI2-NEXT:    retq
  %x = load i256, ptr %in
  %r = mul i256 %x, %x
  store i256 %r, ptr %out
  ret void
}

; full square, 4 limbs -> 8 limbs
define void @sqr_i512_zext_i256(ptr %out, ptr %in) {
; X64-LABEL: sqr_i512_zext_i256:
; X64:       # %bb.0:
; X64-NEXT:    pushq %rbp
; X64-NEXT:    .cfi_def_cfa_offset 16
; X64-NEXT:    pushq %r15
; X64-NEXT:    .cfi_def_cfa_offset 24
; X64-NEXT:    pushq %r14
; X64-NEXT:    .cfi_def_cfa_offset 32
; X64-NEXT:    pushq %r13
; X64-NEXT:    .cfi_def_cfa_offset 40
; X64-NEXT:    pushq %r12
; X64-NEXT:    .cfi_def_cfa_offset 48
; X64-NEXT:    pushq %rbx
; X64-NEXT:    .cfi_def_cfa_offset 56
; X64-NEXT:    .cfi_offset %rbx, -56
; X64-NEXT:    .cfi_offset %r12, -48
; X64-NEXT:    .cfi_offset %r13, -40
; X64-NEXT:    .cfi_offset %r14, -32
; X64-NEXT:    .cfi_offset %r15, -24
; X64-NEXT:    .cfi_offset %rbp, -16
; X64-NEXT:    movq 16(%rsi), %r8
; X64-NEXT:    movq 24(%rsi), %r14
; X64-NEXT:    movq (%rsi), %r10
; X64-NEXT:    movq 8(%rsi), %r9
; X64-NEXT:    movq %r10, %rax
; X64-NEXT:    mulq %r10
; X64-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rax, (%rdi)
; X64-NEXT:    movq %r10, %rax
; X64-NEXT:    mulq %r14
; X64-NEXT:    movq %rdx, %rsi
; X64-NEXT:    movq %rax, %r11
; X64-NEXT:    movq %r10, %rax
; X64-NEXT:    mulq %r8
; X64-NEXT:    movq %rdx, %r13
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %r9, %rax
; X64-NEXT:    mulq %r14
; X64-NEXT:    movq %r14, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rax, %rcx
; X64-NEXT:    movq %rdx, %rbp
; X64-NEXT:    addq %r11, %r13
; X64-NEXT:    adcq %rsi, %rcx
; X64-NEXT:    adcq $0, %rbp
; X64-NEXT:    movq %r10, %rax
; X64-NEXT:    mulq %r9
; X64-NEXT:    movq %rdx, %rbx
; X64-NEXT:    movq %rax, %r15
; X64-NEXT:    movq %r9, %rax
; X64-NEXT:    mulq %r8
; X64-NEXT:    movq %rdx, %r11
; X64-NEXT:    movq %rax, %r12
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    mulq %r14
; X64-NEXT:    movq %rax, %r14
; X64-NEXT:    movq %rdx, %r10
; X64-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %rbx # 8-byte Folded Reload
; X64-NEXT:    adcq %r13, %r12
; X64-NEXT:    adcq %rcx, %r11
; X64-NEXT:    adcq %rbp, %r14
; X64-NEXT:    adcq $0, %r10
; X64-NEXT:    movq %r10, %r13
; X64-NEXT:    shldq $1, %r14, %r13
; X64-NEXT:    shldq $1, %r11, %r14
; X64-NEXT:    shrq $63, %r10
; X64-NEXT:    shldq $1, %r12, %r11
; X64-NEXT:    shldq $1, %rbx, %r12
; X64-NEXT:    shldq $1, %r15, %rbx
; X64-NEXT:    addq %r15, %r15
; X64-NEXT:    movq %r9, %rax
; X64-NEXT:    mulq %r9
; X64-NEXT:    movq %rdx, %rcx
; X64-NEXT:    movq %rax, %rsi
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    mulq %r8
; X64-NEXT:    movq %rdx, %r8
; X64-NEXT:    movq %rax, %r9
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    mulq %rax
; X64-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %r15 # 8-byte Folded Reload
; X64-NEXT:    movq %r15, 8(%rdi)
; X64-NEXT:    adcq %rbx, %rsi
; X64-NEXT:    movq %rsi, 16(%rdi)
; X64-NEXT:    adcq %r12, %rcx
; X64-NEXT:    movq %rcx, 24(%rdi)
; X64-NEXT:    adcq %r11, %r9
; X64-NEXT:    movq %r9, 32(%rdi)
; X64-NEXT:    adcq %r14, %r8
; X64-NEXT:    movq %r8, 40(%rdi)
; X64-NEXT:    adcq %r13, %rax
; X64-NEXT:    movq %rax, 48(%rdi)
; X64-NEXT:    adcq %r10, %rdx
; X64-NEXT:    movq %rdx, 56(%rdi)
; X64-NEXT:    popq %rbx
; X64-NEXT:    .cfi_def_cfa_offset 48
; X64-NEXT:    popq %r12
; X64-NEXT:    .cfi_def_cfa_offset 40
; X64-NEXT:    popq %r13
; X64-NEXT:    .cfi_def_cfa_offset 32
; X64-NEXT:    popq %r14
; X64-NEXT:    .cfi_def_cfa_offset 24
; X64-NEXT:    popq %r15
; X64-NEXT:    .cfi_def_cfa_offset 16
; X64-NEXT:    popq %rbp
; X64-NEXT:    .cfi_def_cfa_offset 8
; X64-NEXT:    retq
;
; BMI2-LABEL: sqr_i512_zext_i256:
; BMI2:       # %bb.0:
; BMI2-NEXT:    pushq %rbp
; BMI2-NEXT:    .cfi_def_cfa_offset 16
; BMI2-NEXT:    pushq %r15
; BMI2-NEXT:    .cfi_def_cfa_offset 24
; BMI2-NEXT:    pushq %r14
; BMI2-NEXT:    .cfi_def_cfa_offset 32
; BMI2-NEXT:    pushq %r13
; BMI2-NEXT:    .cfi_def_cfa_offset 40
; BMI2-NEXT:    pushq %r12
; BMI2-NEXT:    .cfi_def_cfa_offset 48
; BMI2-NEXT:    pushq %rbx
; BMI2-NEXT:    .cfi_def_cfa_offset 56
; BMI2-NEXT:    .cfi_offset %rbx, -56
; BMI2-NEXT:    .cfi_offset %r12, -48
; BMI2-NEXT:    .cfi_offset %r13, -40
; BMI2-NEXT:    .cfi_offset %r14, -32
; BMI2-NEXT:    .cfi_offset %r15, -24
; BMI2-NEXT:    .cfi_offset %rbp, -16
; BMI2-NEXT:    movq 16(%rsi), %rcx
; BMI2-NEXT:    movq 24(%rsi), %rax
; BMI2-NEXT:    movq (%rsi), %r8
; BMI2-NEXT:    movq 8(%rsi), %rsi
; BMI2-NEXT:    movq %r8, %rdx
; BMI2-NEXT:    mulxq %r8, %rdx, %r9
; BMI2-NEXT:    movq %r9, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; BMI2-NEXT:    movq %rdx, (%rdi)
; BMI2-NEXT:    movq %r8, %rdx
; BMI2-NEXT:    mulxq %rax, %r11, %r10
; BMI2-NEXT:    mulxq %rcx, %r9, %r13
; BMI2-NEXT:    movq %rsi, %rdx
; BMI2-NEXT:    mulxq %rax, %rbp, %rbx
; BMI2-NEXT:    addq %r11, %r13
; BMI2-NEXT:    adcq %r10, %rbp
; BMI2-NEXT:    adcq $0, %rbx
; BMI2-NEXT:    movq %r8, %rdx
; BMI2-NEXT:    mulxq %rsi, %r12, %r15
; BMI2-NEXT:    movq %rsi, %rdx
; BMI2-NEXT:    mulxq %rcx, %r14, %r11
; BMI2-NEXT:    movq %rcx, %rdx
; BMI2-NEXT:    mulxq %rax, %r10, %r8
; BMI2-NEXT:    addq %r9, %r15
; BMI2-NEXT:    adcq %r13, %r14
; BMI2-NEXT:    adcq %rbp, %r11
; BMI2-NEXT:    adcq %rbx, %r10
; BMI2-NEXT:    adcq $0, %r8
; BMI2-NEXT:    movq %r8, %rbx
; BMI2-NEXT:    shldq $1, %r10, %rbx
; BMI2-NEXT:    shldq $1, %r11, %r10
; BMI2-NEXT:    shrq $63, %r8
; BMI2-NEXT:    shldq $1, %r14, %r11
; BMI2-NEXT:    shldq $1, %r15, %r14
; BMI2-NEXT:    shldq $1, %r12, %r15
; BMI2-NEXT:    addq %r12, %r12
; BMI2-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %r12 # 8-byte Folded Reload
; BMI2-NEXT:    movq %r12, 8(%rdi)
; BMI2-NEXT:    movq %rsi, %rdx
; BMI2-NEXT:    mulxq %rsi, %rdx, %rsi
; BMI2-NEXT:    adcq %r15, %rdx
; BMI2-NEXT:    movq %rdx, 16(%rdi)
; BMI2-NEXT:    adcq %r14, %rsi
; BMI2-NEXT:    movq %rsi, 24(%rdi)
; BMI2-NEXT:    movq %rcx, %rdx
; BMI2-NEXT:    mulxq %rcx, %rcx, %rdx
; BMI2-NEXT:    adcq %r11, %rcx
; BMI2-NEXT:    movq %rcx, 32(%rdi)
; BMI2-NEXT:    adcq %r10, %rdx
; BMI2-NEXT:    movq %rdx, 40(%rdi)
; BMI2-NEXT:    movq %rax, %rdx
; BMI2-NEXT:    mulxq %rax, %rax, %rcx
; BMI2-NEXT:    adcq %rbx, %rax
; BMI2-NEXT:    movq %rax, 48(%rdi)
; BMI2-NEXT:    adcq %r8, %rcx
; BMI2-NEXT:    movq %rcx, 56(%rdi)
; BMI2-NEXT:    popq %rbx
; BMI2-NEXT:    .cfi_def_cfa_offset 48
; BMI2-NEXT:    popq %r12
; BMI2-NEXT:    .cfi_def_cfa_offset 40
; BMI2-NEXT:    popq %r13
; BMI2-NEXT:    .cfi_def_cfa_offset 32
; BMI2-NEXT:    popq %r14
; BMI2-NEXT:    .cfi_def_cfa_offset 24
; BMI2-NEXT:    popq %r15
; BMI2-NEXT:    .cfi_def_cfa_offset 16
; BMI2-NEXT:    popq %rbp
; BMI2-NEXT:    .cfi_def_cfa_offset 8
; BMI2-NEXT:    retq
  %x = load i256, ptr %in
  %z = zext i256 %x to i512
  %r = mul i512 %z, %z
  store i512 %r, ptr %out
  ret void
}

; full square through a promoted type (i768 -> i1024), 6 limbs -> 12 limbs
define void @sqr_i768_zext_i384(ptr %out, ptr %in) {
; X64-LABEL: sqr_i768_zext_i384:
; X64:       # %bb.0:
; X64-NEXT:    pushq %rbp
; X64-NEXT:    .cfi_def_cfa_offset 16
; X64-NEXT:    pushq %r15
; X64-NEXT:    .cfi_def_cfa_offset 24
; X64-NEXT:    pushq %r14
; X64-NEXT:    .cfi_def_cfa_offset 32
; X64-NEXT:    pushq %r13
; X64-NEXT:    .cfi_def_cfa_offset 40
; X64-NEXT:    pushq %r12
; X64-NEXT:    .cfi_def_cfa_offset 48
; X64-NEXT:    pushq %rbx
; X64-NEXT:    .cfi_def_cfa_offset 56
; X64-NEXT:    .cfi_offset %rbx, -56
; X64-NEXT:    .cfi_offset %r12, -48
; X64-NEXT:    .cfi_offset %r13, -40
; X64-NEXT:    .cfi_offset %r14, -32
; X64-NEXT:    .cfi_offset %r15, -24
; X64-NEXT:    .cfi_offset %rbp, -16
; X64-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq 16(%rsi), %rbp
; X64-NEXT:    movq 24(%rsi), %r13
; X64-NEXT:    movq 32(%rsi), %r14
; X64-NEXT:    movq 40(%rsi), %rcx
; X64-NEXT:    movq (%rsi), %rbx
; X64-NEXT:    movq 8(%rsi), %r12
; X64-NEXT:    movq %rbx, %rax
; X64-NEXT:    mulq %rbx
; X64-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rax, (%rdi)
; X64-NEXT:    movq %rbx, %rax
; X64-NEXT:    movq %rcx, %rdi
; X64-NEXT:    mulq %rcx
; X64-NEXT:    movq %rdx, %rcx
; X64-NEXT:    movq %rax, %rsi
; X64-NEXT:    movq %rbx, %rax
; X64-NEXT:    mulq %r14
; X64-NEXT:    movq %r14, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rdx, %r10
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %r12, %rax
; X64-NEXT:    mulq %rdi
; X64-NEXT:    movq %rdi, %r9
; X64-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rax, %rdi
; X64-NEXT:    movq %rdx, %r11
; X64-NEXT:    addq %rsi, %r10
; X64-NEXT:    adcq %rcx, %rdi
; X64-NEXT:    adcq $0, %r11
; X64-NEXT:    movq %rbx, %rax
; X64-NEXT:    mulq %r13
; X64-NEXT:    movq %rdx, %rcx
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %r12, %rax
; X64-NEXT:    movq %r12, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    mulq %r14
; X64-NEXT:    movq %rdx, %rsi
; X64-NEXT:    movq %rax, %r14
; X64-NEXT:    movq %rbp, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rbp, %rax
; X64-NEXT:    mulq %r9
; X64-NEXT:    movq %rax, %r15
; X64-NEXT:    movq %rdx, %r9
; X64-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Folded Reload
; X64-NEXT:    adcq %r10, %r14
; X64-NEXT:    adcq %rdi, %rsi
; X64-NEXT:    adcq %r11, %r15
; X64-NEXT:    adcq $0, %r9
; X64-NEXT:    movq %rbx, %rax
; X64-NEXT:    mulq %rbp
; X64-NEXT:    movq %rdx, %r8
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %r12, %rax
; X64-NEXT:    movq %r13, %rdi
; X64-NEXT:    mulq %r13
; X64-NEXT:    movq %rdx, %r12
; X64-NEXT:    movq %rax, %r13
; X64-NEXT:    movq %rbp, %rax
; X64-NEXT:    mulq {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Folded Reload
; X64-NEXT:    movq %rdx, %rbp
; X64-NEXT:    movq %rax, %r11
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    mulq {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Folded Reload
; X64-NEXT:    movq %rax, %r10
; X64-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %r8 # 8-byte Folded Reload
; X64-NEXT:    movq %r8, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    adcq %rcx, %r13
; X64-NEXT:    movq %r13, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    adcq %r14, %r12
; X64-NEXT:    movq %r12, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    adcq %rsi, %r11
; X64-NEXT:    adcq %r15, %rbp
; X64-NEXT:    movq %rbp, %r15
; X64-NEXT:    adcq %r9, %r10
; X64-NEXT:    adcq $0, %rdx
; X64-NEXT:    movq %rdx, %r9
; X64-NEXT:    movq %rbx, %rax
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; X64-NEXT:    mulq %rcx
; X64-NEXT:    movq %rdx, %rsi
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rcx, %rax
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r8 # 8-byte Reload
; X64-NEXT:    mulq %r8
; X64-NEXT:    movq %rdx, %rcx
; X64-NEXT:    movq %rax, %r12
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    mulq %rdi
; X64-NEXT:    movq %rdx, %r14
; X64-NEXT:    movq %rax, %rbp
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r8 # 8-byte Reload
; X64-NEXT:    mulq %r8
; X64-NEXT:    movq %rdx, %rbx
; X64-NEXT:    movq %rax, %r13
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; X64-NEXT:    mulq %rdx
; X64-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Folded Reload
; X64-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %r12 # 8-byte Folded Reload
; X64-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Folded Reload
; X64-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %rbp # 8-byte Folded Reload
; X64-NEXT:    adcq %r11, %r14
; X64-NEXT:    adcq %r15, %r13
; X64-NEXT:    adcq %r10, %rbx
; X64-NEXT:    adcq %r9, %rax
; X64-NEXT:    adcq $0, %rdx
; X64-NEXT:    movq %rdx, %r9
; X64-NEXT:    shldq $1, %rax, %r9
; X64-NEXT:    movq %r9, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    shldq $1, %rbx, %rax
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    shldq $1, %r13, %rbx
; X64-NEXT:    movq %rbx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    shldq $1, %r14, %r13
; X64-NEXT:    shrq $63, %rdx
; X64-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    shldq $1, %rbp, %r14
; X64-NEXT:    movq %r14, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    shldq $1, %rcx, %rbp
; X64-NEXT:    shldq $1, %r12, %rcx
; X64-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    shldq $1, %rsi, %r12
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r9 # 8-byte Reload
; X64-NEXT:    shldq $1, %r9, %rsi
; X64-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    addq %r9, %r9
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    mulq %rax
; X64-NEXT:    movq %rdx, %r15
; X64-NEXT:    movq %rax, %rcx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    mulq %rax
; X64-NEXT:    movq %rdx, %r11
; X64-NEXT:    movq %rax, %rsi
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    mulq %rdi
; X64-NEXT:    movq %rdx, %rbx
; X64-NEXT:    movq %rax, %rdi
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    mulq %r8
; X64-NEXT:    movq %rdx, %r14
; X64-NEXT:    movq %rax, %r8
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    mulq %rax
; X64-NEXT:    movq %rax, %r10
; X64-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %r9 # 8-byte Folded Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    movq %r9, 8(%rax)
; X64-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Folded Reload
; X64-NEXT:    movq %rcx, 16(%rax)
; X64-NEXT:    adcq %r12, %r15
; X64-NEXT:    movq %r15, 24(%rax)
; X64-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Folded Reload
; X64-NEXT:    movq %rsi, 32(%rax)
; X64-NEXT:    adcq %rbp, %r11
; X64-NEXT:    movq %r11, 40(%rax)
; X64-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Folded Reload
; X64-NEXT:    movq %rdi, 48(%rax)
; X64-NEXT:    adcq %r13, %rbx
; X64-NEXT:    movq %rbx, 56(%rax)
; X64-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %r8 # 8-byte Folded Reload
; X64-NEXT:    movq %r8, 64(%rax)
; X64-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %r14 # 8-byte Folded Reload
; X64-NEXT:    movq %r14, 72(%rax)
; X64-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %r10 # 8-byte Folded Reload
; X64-NEXT:    movq %r10, 80(%rax)
; X64-NEXT:    adcq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Folded Reload
; X64-NEXT:    movq %rdx, 88(%rax)
; X64-NEXT:    popq %rbx
; X64-NEXT:    .cfi_def_cfa_offset 48
; X64-NEXT:    popq %r12
; X64-NEXT:    .cfi_def_cfa_offset 40
; X64-NEXT:    popq %r13
; X64-NEXT:    .cfi_def_cfa_offset 32
; X64-NEXT:    popq %r14
; X64-NEXT:    .cfi_def_cfa_offset 24
; X64-NEXT:    popq %r15
; X64-NEXT:    .cfi_def_cfa_offset 16
; X64-NEXT:    popq %rbp
; X64-NEXT:    .cfi_def_cfa_offset 8
; X64-NEXT:    retq
;
; BMI2-LABEL: sqr_i768_zext_i384:
; BMI2:       # %bb.0:
; BMI2-NEXT:    pushq %rbp
; BMI2-NEXT:    .cfi_def_cfa_offset 16
; BMI2-NEXT:    pushq %r15
; BMI2-NEXT:    .cfi_def_cfa_offset 24
; BMI2-NEXT:    pushq %r14
; BMI2-NEXT:    .cfi_def_cfa_offset 32
; BMI2-NEXT:    pushq %r13
; BMI2-NEXT:    .cfi_def_cfa_offset 40
; BMI2-NEXT:    pushq %r12
; BMI2-NEXT:    .cfi_def_cfa_offset 48
; BMI2-NEXT:    pushq %rbx
; BMI2-NEXT:    .cfi_def_cfa_offset 56
; BMI2-NEXT:    .cfi_offset %rbx, -56
; BMI2-NEXT:    .cfi_offset %r12, -48
; BMI2-NEXT:    .cfi_offset %r13, -40
; BMI2-NEXT:    .cfi_offset %r14, -32
; BMI2-NEXT:    .cfi_offset %r15, -24
; BMI2-NEXT:    .cfi_offset %rbp, -16
; BMI2-NEXT:    movq 16(%rsi), %rax
; BMI2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; BMI2-NEXT:    movq 24(%rsi), %r13
; BMI2-NEXT:    movq 32(%rsi), %r14
; BMI2-NEXT:    movq 40(%rsi), %rcx
; BMI2-NEXT:    movq (%rsi), %r10
; BMI2-NEXT:    movq 8(%rsi), %r12
; BMI2-NEXT:    movq %r10, %rdx
; BMI2-NEXT:    mulxq %r10, %rax, %rdx
; BMI2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; BMI2-NEXT:    movq %rax, (%rdi)
; BMI2-NEXT:    movq %r10, %rdx
; BMI2-NEXT:    movq %rcx, %rsi
; BMI2-NEXT:    mulxq %rcx, %rcx, %rax
; BMI2-NEXT:    mulxq %r14, %r8, %r9
; BMI2-NEXT:    movq %r14, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; BMI2-NEXT:    movq %r12, %rdx
; BMI2-NEXT:    mulxq %rsi, %r11, %rbx
; BMI2-NEXT:    movq %rsi, %r15
; BMI2-NEXT:    addq %rcx, %r9
; BMI2-NEXT:    adcq %rax, %r11
; BMI2-NEXT:    adcq $0, %rbx
; BMI2-NEXT:    movq %r10, %rdx
; BMI2-NEXT:    mulxq %r13, %rax, %rsi
; BMI2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; BMI2-NEXT:    movq %r13, %rcx
; BMI2-NEXT:    addq %r8, %rsi
; BMI2-NEXT:    movq %r12, %rdx
; BMI2-NEXT:    movq %r12, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; BMI2-NEXT:    mulxq %r14, %r8, %rbp
; BMI2-NEXT:    adcq %r9, %r8
; BMI2-NEXT:    adcq %r11, %rbp
; BMI2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Reload
; BMI2-NEXT:    movq %r13, %rdx
; BMI2-NEXT:    mulxq %r15, %r9, %r11
; BMI2-NEXT:    movq %r15, %r14
; BMI2-NEXT:    movq %r15, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; BMI2-NEXT:    adcq %rbx, %r9
; BMI2-NEXT:    adcq $0, %r11
; BMI2-NEXT:    movq %r10, %rdx
; BMI2-NEXT:    mulxq %r13, %rdx, %rax
; BMI2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; BMI2-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Folded Reload
; BMI2-NEXT:    movq %r12, %rdx
; BMI2-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; BMI2-NEXT:    mulxq %rcx, %r15, %rbx
; BMI2-NEXT:    adcq %rsi, %r15
; BMI2-NEXT:    adcq %r8, %rbx
; BMI2-NEXT:    movq %r13, %rdx
; BMI2-NEXT:    mulxq {{[-0-9]+}}(%r{{[sb]}}p), %r13, %r12 # 8-byte Folded Reload
; BMI2-NEXT:    adcq %rbp, %r13
; BMI2-NEXT:    adcq %r9, %r12
; BMI2-NEXT:    movq %rcx, %rdx
; BMI2-NEXT:    mulxq %r14, %r9, %r8
; BMI2-NEXT:    adcq %r11, %r9
; BMI2-NEXT:    adcq $0, %r8
; BMI2-NEXT:    movq %r10, %rdx
; BMI2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; BMI2-NEXT:    mulxq %rcx, %rsi, %r14
; BMI2-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %r14 # 8-byte Folded Reload
; BMI2-NEXT:    movq %rcx, %rdx
; BMI2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; BMI2-NEXT:    mulxq %rcx, %r11, %rbp
; BMI2-NEXT:    adcq %rax, %r11
; BMI2-NEXT:    adcq %r15, %rbp
; BMI2-NEXT:    movq %rcx, %rdx
; BMI2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; BMI2-NEXT:    mulxq %rax, %rcx, %r15
; BMI2-NEXT:    adcq %rbx, %rcx
; BMI2-NEXT:    adcq %r13, %r15
; BMI2-NEXT:    movq %rax, %rdx
; BMI2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r10 # 8-byte Reload
; BMI2-NEXT:    mulxq %r10, %rax, %rbx
; BMI2-NEXT:    adcq %r12, %rax
; BMI2-NEXT:    adcq %r9, %rbx
; BMI2-NEXT:    movq %r10, %rdx
; BMI2-NEXT:    movq %r10, %r9
; BMI2-NEXT:    mulxq {{[-0-9]+}}(%r{{[sb]}}p), %r13, %r10 # 8-byte Folded Reload
; BMI2-NEXT:    adcq %r8, %r13
; BMI2-NEXT:    adcq $0, %r10
; BMI2-NEXT:    movq %r10, %r12
; BMI2-NEXT:    shldq $1, %r13, %r12
; BMI2-NEXT:    shldq $1, %rbx, %r13
; BMI2-NEXT:    shldq $1, %rax, %rbx
; BMI2-NEXT:    shldq $1, %r15, %rax
; BMI2-NEXT:    shrq $63, %r10
; BMI2-NEXT:    shldq $1, %rcx, %r15
; BMI2-NEXT:    shldq $1, %rbp, %rcx
; BMI2-NEXT:    shldq $1, %r11, %rbp
; BMI2-NEXT:    shldq $1, %r14, %r11
; BMI2-NEXT:    shldq $1, %rsi, %r14
; BMI2-NEXT:    addq %rsi, %rsi
; BMI2-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Folded Reload
; BMI2-NEXT:    movq %rsi, 8(%rdi)
; BMI2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; BMI2-NEXT:    mulxq %rdx, %rdx, %rsi
; BMI2-NEXT:    adcq %r14, %rdx
; BMI2-NEXT:    movq %rdx, 16(%rdi)
; BMI2-NEXT:    adcq %r11, %rsi
; BMI2-NEXT:    movq %rsi, 24(%rdi)
; BMI2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; BMI2-NEXT:    mulxq %rdx, %rdx, %rsi
; BMI2-NEXT:    adcq %rbp, %rdx
; BMI2-NEXT:    movq %rdx, 32(%rdi)
; BMI2-NEXT:    adcq %rcx, %rsi
; BMI2-NEXT:    movq %rsi, 40(%rdi)
; BMI2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; BMI2-NEXT:    mulxq %rdx, %rcx, %rdx
; BMI2-NEXT:    adcq %r15, %rcx
; BMI2-NEXT:    movq %rcx, 48(%rdi)
; BMI2-NEXT:    adcq %rax, %rdx
; BMI2-NEXT:    movq %rdx, 56(%rdi)
; BMI2-NEXT:    movq %r9, %rdx
; BMI2-NEXT:    mulxq %r9, %rax, %rcx
; BMI2-NEXT:    adcq %rbx, %rax
; BMI2-NEXT:    movq %rax, 64(%rdi)
; BMI2-NEXT:    adcq %r13, %rcx
; BMI2-NEXT:    movq %rcx, 72(%rdi)
; BMI2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; BMI2-NEXT:    mulxq %rdx, %rax, %rcx
; BMI2-NEXT:    adcq %r12, %rax
; BMI2-NEXT:    movq %rax, 80(%rdi)
; BMI2-NEXT:    adcq %r10, %rcx
; BMI2-NEXT:    movq %rcx, 88(%rdi)
; BMI2-NEXT:    popq %rbx
; BMI2-NEXT:    .cfi_def_cfa_offset 48
; BMI2-NEXT:    popq %r12
; BMI2-NEXT:    .cfi_def_cfa_offset 40
; BMI2-NEXT:    popq %r13
; BMI2-NEXT:    .cfi_def_cfa_offset 32
; BMI2-NEXT:    popq %r14
; BMI2-NEXT:    .cfi_def_cfa_offset 24
; BMI2-NEXT:    popq %r15
; BMI2-NEXT:    .cfi_def_cfa_offset 16
; BMI2-NEXT:    popq %rbp
; BMI2-NEXT:    .cfi_def_cfa_offset 8
; BMI2-NEXT:    retq
  %x = load i384, ptr %in
  %z = zext i384 %x to i768
  %r = mul i768 %z, %z
  store i768 %r, ptr %out
  ret void
}

; sign-extended operand: no known-zero limbs, truncated 4 x 4
define void @sqr_i256_sext_i128(ptr %out, ptr %in) {
; X64-LABEL: sqr_i256_sext_i128:
; X64:       # %bb.0:
; X64-NEXT:    pushq %rbx
; X64-NEXT:    .cfi_def_cfa_offset 16
; X64-NEXT:    .cfi_offset %rbx, -16
; X64-NEXT:    movq (%rsi), %r8
; X64-NEXT:    movq 8(%rsi), %rsi
; X64-NEXT:    movq %rsi, %rbx
; X64-NEXT:    sarq $63, %rbx
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    mulq %r8
; X64-NEXT:    movq %rdx, %rcx
; X64-NEXT:    movq %rax, (%rdi)
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    mulq %rbx
; X64-NEXT:    movq %rdx, %r9
; X64-NEXT:    movq %rax, %r10
; X64-NEXT:    addq %rax, %r9
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    mulq %rsi
; X64-NEXT:    movq %rax, %r8
; X64-NEXT:    movq %rdx, %r11
; X64-NEXT:    imulq %rsi, %rbx
; X64-NEXT:    addq %r10, %r11
; X64-NEXT:    adcq %r9, %rbx
; X64-NEXT:    shldq $1, %r11, %rbx
; X64-NEXT:    shldq $1, %rax, %r11
; X64-NEXT:    addq %rax, %r8
; X64-NEXT:    movq %rsi, %rax
; X64-NEXT:    mulq %rsi
; X64-NEXT:    addq %rcx, %r8
; X64-NEXT:    movq %r8, 8(%rdi)
; X64-NEXT:    adcq %r11, %rax
; X64-NEXT:    movq %rax, 16(%rdi)
; X64-NEXT:    adcq %rbx, %rdx
; X64-NEXT:    movq %rdx, 24(%rdi)
; X64-NEXT:    popq %rbx
; X64-NEXT:    .cfi_def_cfa_offset 8
; X64-NEXT:    retq
;
; BMI2-LABEL: sqr_i256_sext_i128:
; BMI2:       # %bb.0:
; BMI2-NEXT:    movq (%rsi), %rdx
; BMI2-NEXT:    movq 8(%rsi), %rax
; BMI2-NEXT:    movq %rax, %rcx
; BMI2-NEXT:    sarq $63, %rcx
; BMI2-NEXT:    mulxq %rdx, %r8, %rsi
; BMI2-NEXT:    movq %r8, (%rdi)
; BMI2-NEXT:    mulxq %rcx, %r8, %r9
; BMI2-NEXT:    addq %r8, %r9
; BMI2-NEXT:    mulxq %rax, %rdx, %r10
; BMI2-NEXT:    imulq %rax, %rcx
; BMI2-NEXT:    addq %r8, %r10
; BMI2-NEXT:    adcq %r9, %rcx
; BMI2-NEXT:    shldq $1, %r10, %rcx
; BMI2-NEXT:    shldq $1, %rdx, %r10
; BMI2-NEXT:    addq %rdx, %rdx
; BMI2-NEXT:    addq %rsi, %rdx
; BMI2-NEXT:    movq %rdx, 8(%rdi)
; BMI2-NEXT:    movq %rax, %rdx
; BMI2-NEXT:    mulxq %rax, %rax, %rdx
; BMI2-NEXT:    adcq %r10, %rax
; BMI2-NEXT:    movq %rax, 16(%rdi)
; BMI2-NEXT:    adcq %rcx, %rdx
; BMI2-NEXT:    movq %rdx, 24(%rdi)
; BMI2-NEXT:    retq
  %x = load i128, ptr %in
  %z = sext i128 %x to i256
  %r = mul i256 %z, %z
  store i256 %r, ptr %out
  ret void
}

; a single limb: one product, not expanded here
define void @sqr_i256_zext_i64(ptr %out, ptr %in) {
; X64-LABEL: sqr_i256_zext_i64:
; X64:       # %bb.0:
; X64-NEXT:    movq (%rsi), %rax
; X64-NEXT:    mulq %rax
; X64-NEXT:    xorps %xmm0, %xmm0
; X64-NEXT:    movaps %xmm0, 16(%rdi)
; X64-NEXT:    movq %rdx, 8(%rdi)
; X64-NEXT:    movq %rax, (%rdi)
; X64-NEXT:    retq
;
; BMI2-LABEL: sqr_i256_zext_i64:
; BMI2:       # %bb.0:
; BMI2-NEXT:    movq (%rsi), %rdx
; BMI2-NEXT:    mulxq %rdx, %rcx, %rax
; BMI2-NEXT:    xorps %xmm0, %xmm0
; BMI2-NEXT:    movaps %xmm0, 16(%rdi)
; BMI2-NEXT:    movq %rax, 8(%rdi)
; BMI2-NEXT:    movq %rcx, (%rdi)
; BMI2-NEXT:    retq
  %x = load i64, ptr %in
  %z = zext i64 %x to i256
  %r = mul i256 %z, %z
  store i256 %r, ptr %out
  ret void
}
